### ISSUE TITLE
Great tips!

### ISSUE THREAD

**Issue by kotAPI** [igrishaev/dos-and-donts#1]
Came here to say that I loved some points here! Thanks!

**Comment by igrishaev** [comment]
Thank you @kotAPI ! Well, it's a bit outdated and I've changed my mind on some topics. Still, some of them are still relevant, I hope.

**Comment by kotAPI** [comment]
> Thank you @kotAPI ! Well, it's a bit outdated and I've changed my mind on some topics. Still, some of them are still relevant, I hope.

Especially the don't argue, be nice, vim vs emacs, python vs X :) 
I'd say these are valid for a lot of time to come
